ChartValues:
  service:
    selector:
      component: yunikorn-scheduler
    type: LoadBalancer
    ports:
    - port: 9889
      targetPort: 9889
HelmChartPath: helm
RuntimeType: Kubernetes
OutputCmd: |-
  export SERVICE_IP=$(kubectl get svc --namespace ${Namespace} ${ReleaseName} -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
  echo "Visit URL: http://$SERVICE_IP/"
ServiceType: private
ArtifactSourceType: HelmChart
ServiceBuildRegion: ap-southeast-1
RepoName: mengjunwei-mjw/yunikorn
RegionId: cn-hangzhou
OutputType: OutputCommand
Owner: mengjunwei-mjw
Branch: feature/quickstart
Platform: github
